# Generated by Django 4.2.10 on 2024-02-20 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fine_tuning_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('completion', models.TextField()),
                ('is_fine_tuned', models.BooleanField(default=False)),
                ('will_be_fine_tuned', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='finetunedmodel',
            name='file_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='finetunedmodel',
            name='fine_tuned_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='finetunedmodel',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='finetunedmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine_tuned_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TraningData',
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='fine_tuned_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='fine_tuning_chatbot.finetunedmodel'),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_datas', to=settings.AUTH_USER_MODEL),
        ),
    ]
