# Generated by Django 4.2.10 on 2024-02-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine_tuning_chatbot', '0002_trainingdata_finetunedmodel_file_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finetunedmodel',
            old_name='fine_tuned_id',
            new_name='fine_tune_id',
        ),
        migrations.AddField(
            model_name='finetunedmodel',
            name='fine_tuned_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
